Name:Wafa Karim Khan

Msc(Data science & Big Data Analytics)

College: B.K Birla College of Arts, Science and Commerce kalyan.

Task1:Implement Data Cleaning and Basic Feature Engineering Techniques to Prepare Data for a Movie Recommendation System.

In [1]:
import pandas as pd

In [2]:
movies_data = pd.read_csv("movies_metadata.csv", low_memory=False)
ratings = pd.read_csv("ratings.csv", low_memory=False)

In [3]:
movies_df = pd.DataFrame(movies_data)
ratings_df = pd.DataFrame(ratings)

In [4]:
movies_df

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

In [5]:
ratings_df

         userId    id  rating   timestamp
0             1   110     1.0  1425941529
1             1   147     4.5  1425942435
2             1   858     5.0  1425941523
3             1  1221     5.0  1425941546
4             1  1246     5.0  1425941556
...         ...   ...     ...         ...
1048570   10656  1608     2.0   906755366
1048571   10656  1610     3.0   906755296
1048572   10656  1614     3.0   906754185
1048573   10656  1616     1.0   906755479
1048574   10656  1617     4.0   906832779

[1048575 rows x 4 columns]

In [6]:
#since we had 2 different datasetsfor movies metadata and separate dataset for ratings.
#and both the datasets had data against the movie id.
#in ratings dataset movies were rated by different users. therefore, single movie has multiple ratings by different users.
#to get the actual mean of those ratings by different users we can group these ratings by movie ids and then get their mean.
rating_grouped_by_id=ratings_df.groupby('id')
rating_grouped_by_id

In [7]:
ratings_mean=rating_grouped_by_id.mean()
ratings_mean

             userId    rating     timestamp
id
1       5188.554271  3.897799  1.119265e+09
2       5259.381089  3.204394  1.100198e+09
3       5225.826307  3.181282  9.703165e+08
4       5064.476636  2.859813  9.443451e+08
5       5356.526656  3.102585  9.967256e+08
...             ...       ...           ...
175975  5226.000000  4.000000  1.501020e+09
176165  4916.000000  3.000000  1.501614e+09
176211  7933.500000  3.750000  1.501630e+09
176219  7925.000000  2.500000  1.501546e+09
176271   837.000000  5.000000  1.501766e+09

[20499 rows x 3 columns]

In [8]:
#Delet the columns which are not required
ratings_mean.drop(columns='timestamp', inplace=True)
ratings_mean.drop(columns='userId', inplace=True)

In [9]:
rating_mean_df = pd.DataFrame(ratings_mean)
rating_mean_df

          rating
id
1       3.897799
2       3.204394
3       3.181282
4       2.859813
5       3.102585
...          ...
175975  4.000000
176165  3.000000
176211  3.750000
176219  2.500000
176271  5.000000

[20499 rows x 1 columns]

In [10]:
#Removing outliers data since column id contains some dates in approx 3 rows therefore removing the row entirely.
rows_to_delete = []
for idx, value in enumerate(movies_df['id']):
    try:
        int(value)  # Try to parse value to int
    except ValueError:  # If parsing fails, mark row for deletion
        rows_to_delete.append(idx)

# Drop rows marked for deletion
movies_df = movies_df.drop(rows_to_delete)

In [11]:
#since id had some dates entries for some of the rows which are deleted in previous step, 
#initially python and pandas inferred its column type as object, therefore now setting datatype again back to int64.
movies_df['id'] = movies_df['id'].astype('int64')

In [12]:
#now that we have ratings in another dataframe and movies metadata in another merging the both based on id.
#and with left join to ensure that we only get the ratings for which we have data in movies dataframe.
movies_w_rating = pd.merge(movies_df,rating_mean_df, on="id", how="left")
movies_w_rating

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,rating
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,3.454545
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,4.125000
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,NaN
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,NaN
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45458,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0,NaN
45459,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0,3.000000
45460,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0,NaN
45461,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0,NaN
45462,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0,NaN

In [13]:
movies_w_rating['rating'].isnull().value_counts()

rating
True     40377
False     5086
Name: count, dtype: int64

In [14]:
#for some of the movies we dont have ratings available, setting their values as mean of all the available ratings values.
import numpy as np
movies_w_rating["rating"].replace(np.nan,np.mean(movies_w_rating["rating"]),inplace=True)
movies_w_rating

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,rating
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,3.454545
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,4.125000
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,3.271217
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,3.271217
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0,3.271217
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45458,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0,3.271217
45459,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0,3.000000
45460,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0,3.271217
45461,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0,3.271217
45462,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0,3.271217

In [15]:
movies_w_rating.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   3
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      3
runtime                    260
spoken_languages             3
status                      84
tagline                  25051
title                        3
video                        3
vote_average                 3
vote_count                   3
rating                       0
dtype: int64

In [16]:
#Delete the columns which are not required for recommendation 
movies_w_rating.drop(columns='homepage', inplace=True)
movies_w_rating.drop(columns='tagline', inplace=True)
movies_w_rating.drop(columns='overview', inplace=True)
movies_w_rating.drop(columns='poster_path', inplace=True)
movies_w_rating.drop(columns='imdb_id', inplace=True)

In [17]:
#Replace null values with suitable values:
movies_w_rating["original_language"].replace(np.nan,"en",inplace=True)
movies_w_rating["popularity"].replace(np.nan,"not available",inplace=True)
movies_w_rating["production_companies"].replace(np.nan,"not availabe",inplace=True)
movies_w_rating["production_countries"].replace(np.nan,"USA",inplace=True)
movies_w_rating["release_date"].replace(np.nan,"20-08-1997",inplace=True)
movies_w_rating["revenue"].replace(np.nan,np.mean(movies_w_rating["revenue"]),inplace=True)
movies_w_rating["runtime"].replace(np.nan,np.mean(movies_w_rating["runtime"]),inplace=True)
movies_w_rating["spoken_languages"].replace(np.nan,"en",inplace=True)
movies_w_rating["status"].replace(np.nan,"Released",inplace=True)
movies_w_rating["title"].replace(np.nan,"not availabe",inplace=True)
movies_w_rating["video"].replace(np.nan,False,inplace=True)
movies_w_rating["vote_average"].replace(np.nan,np.mean(movies_w_rating["vote_average"]),inplace=True)
movies_w_rating["vote_count"].replace(np.nan,np.mean(movies_w_rating["vote_count"]),inplace=True)
movies_w_rating["belongs_to_collection"].replace(np.nan,"not availabe",inplace=True)

In [18]:
#Now the data is cleaned
movies_w_rating.isnull().sum()

adult                    0
belongs_to_collection    0
budget                   0
genres                   0
id                       0
original_language        0
original_title           0
popularity               0
production_companies     0
production_countries     0
release_date             0
revenue                  0
runtime                  0
spoken_languages         0
status                   0
title                    0
video                    0
vote_average             0
vote_count               0
rating                   0
dtype: int64

In [28]:
movies_w_rating

,adult,belongs_to_collection,budget,genres,id,original_language,original_title,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,title,video,vote_average,vote_count,rating
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,en,Toy Story,21.946943,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Toy Story,False,7.7,5415.0,3.454545
1,False,not availabe,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,en,Jumanji,17.015539,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Jumanji,False,6.9,2413.0,4.125000
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,en,Grumpier Old Men,11.7129,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Grumpier Old Men,False,6.5,92.0,3.271217
3,False,not availabe,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,en,Waiting to Exhale,3.859495,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Waiting to Exhale,False,6.1,34.0,3.271217
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",11862,en,Father of the Bride Part II,8.387519,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Father of the Bride Part II,False,5.7,173.0,3.271217
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45458,False,not availabe,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",439050,fa,رگ خواب,0.072051,[],"[{'iso_3166_1': 'IR', 'name': 'Iran'}]",20-08-1997,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Subdue,False,4.0,1.0,3.271217
45459,False,not availabe,0,"[{'id': 18, 'name': 'Drama'}]",111109,tl,Siglo ng Pagluluwal,0.178241,"[{'name': 'Sine Olivia', 'id': 19653}]","[{'iso_3166_1': 'PH', 'name': 'Philippines'}]",2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,Century of Birthing,False,9.0,3.0,3.000000
45460,False,not availabe,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",67758,en,Betrayal,0.903007,"[{'name': 'American World Pictures', 'id': 6165}]","[{'iso_3166_1': 'US', 'name': 'United States o...",2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Betrayal,False,3.8,6.0,3.271217
45461,False,not availabe,0,[],227506,en,Satana likuyushchiy,0.003503,"[{'name': 'Yermoliev', 'id': 88753}]","[{'iso_3166_1': 'RU', 'name': 'Russia'}]",1917-10-21,0.0,87.0,[],Released,Satan Triumphant,False,0.0,0.0,3.271217
45462,False,not availabe,0,[],461257,en,Queerama,0.163015,[],"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Queerama,False,0.0,0.0,3.271217

In [20]:
#Now we feature engineering that are relevent for making better recommendation
#Suppose user had watched movies whose id's are 8012, 11443, 11010
user_watched_movies_id = [8012, 11443, 11010]
#first we will find out avg of runtime and ratings
watched_movies_df = movies_w_rating[movies_w_rating['id'].isin(user_watched_movies_id)]
avg_runtime = watched_movies_df['runtime'].mean()
avg_rating = watched_movies_df['rating'].mean()
print('Average(Runtime):',avg_runtime)
print('Average(Rating):',avg_rating)

Average(Runtime): 110.66666666666667
Average(Rating): 3.414144772267289

In [21]:
#now we find the genre of the watched ids
watched_genres = []
for genres_list in watched_movies_df['genres']:
    print(genres_list)

[{'id': 35, 'name': 'Comedy'}, {'id': 53, 'name': 'Thriller'}, {'id': 80, 'name': 'Crime'}]
[{'id': 28, 'name': 'Action'}, {'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}, {'id': 36, 'name': 'History'}]
[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]

In [22]:

import json
watched_genres = []
for genres_list in watched_movies_df['genres']:
    g_list = json.loads(genres_list.replace("'", "\""))
    for genre in g_list:
        print(genre)
        watched_genres.append(genre['name'])

{'id': 35, 'name': 'Comedy'}
{'id': 53, 'name': 'Thriller'}
{'id': 80, 'name': 'Crime'}
{'id': 28, 'name': 'Action'}
{'id': 80, 'name': 'Crime'}
{'id': 18, 'name': 'Drama'}
{'id': 36, 'name': 'History'}
{'id': 35, 'name': 'Comedy'}
{'id': 18, 'name': 'Drama'}
{'id': 10749, 'name': 'Romance'}

In [23]:
watched_genres = list(set(watched_genres))
watched_genres

['Crime', 'History', 'Romance', 'Action', 'Drama', 'Thriller', 'Comedy']

In [24]:
# Convert each JSON string in the 'genres' column to a list of dictionaries
genres_list = movies_w_rating['genres'].apply(lambda x: json.loads(x.replace("'", "\"")))

# Check if any of the genres in the movie are in the list of watched genres
is_in_watched_genres = genres_list.apply(lambda x: any(genre['name'] in watched_genres for genre in x))

is_in_watched_genres

0         True
1        False
2         True
3         True
4         True
         ...
45458     True
45459     True
45460     True
45461    False
45462    False
Name: genres, Length: 45463, dtype: bool

In [25]:
# here we will set the criteria on the basis of which we recommend the movies:
# Criteria 1 : Check if the movies genre matches the user's fav genres i.e. his already watched movie genres.
# Criteria 2 : Check for the average runtime of the user's already watched movies +- 10 mins.
# Criteria 3 : Check if the rating of the movie is greater than or equal to user's already watched movies average rating.
# Criteria 4 : From all the available / matched movies, we will recommend the most popular movies to the user.
recommended_movies = movies_w_rating[
                            (is_in_watched_genres) & # Criteria 1
                            (movies_w_rating['runtime'] >= avg_runtime - 10) & # Criteria 2 -10 mins
                            (movies_w_rating['runtime'] <= avg_runtime + 10) & # Criteria 2 +10 mins
                            (movies_w_rating['rating'] >= avg_rating)] # Criteria 3 
recommended_movies

,adult,belongs_to_collection,budget,genres,id,original_language,original_title,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,title,video,vote_average,vote_count,rating
14,False,not availabe,98000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",1408,en,Cutthroat Island,7.284477,"[{'name': 'Le Studio Canal+', 'id': 183}, {'na...","[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...",1995-12-22,10017322.0,119.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Cutthroat Island,False,5.7,137.0,3.692593
20,False,"{'id': 91698, 'name': 'Chili Palmer Collection...",30250000,"[{'id': 35, 'name': 'Comedy'}, {'id': 53, 'nam...",8012,en,Get Shorty,12.669608,"[{'name': 'Jersey Films', 'id': 216}, {'name':...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-20,115101622.0,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Get Shorty,False,6.4,305.0,3.700000
49,False,not availabe,6000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",629,en,The Usual Suspects,16.302466,"[{'name': 'Blue Parrot Productions', 'id': 361...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-07-19,23341568.0,106.0,"[{'iso_639_1': 'es', 'name': 'Español'}, {'iso...",Released,The Usual Suspects,False,8.1,3334.0,4.000000
160,False,"{'id': 9649, 'name': 'Mexico Trilogy', 'poster...",7000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",8068,en,Desperado,6.950458,"[{'name': 'Columbia Pictures', 'id': 5}, {'nam...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-08-25,25405445.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Desperado,False,6.8,898.0,4.500000
161,False,not availabe,27000000,"[{'id': 18, 'name': 'Drama'}, {'id': 9648, 'na...",8512,en,Devil in a Blue Dress,4.646132,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-09-15,16140822.0,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Devil in a Blue Dress,False,6.3,88.0,3.461538
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43680,False,not availabe,0,"[{'id': 80, 'name': 'Crime'}, {'id': 27, 'name...",27316,ko,거울 속으로,2.424021,"[{'name': 'Key Plus Pictures', 'id': 4663}]","[{'iso_3166_1': 'KR', 'name': 'South Korea'}]",2003-08-14,0.0,113.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,Into the Mirror,False,6.1,23.0,3.500000
43716,False,not availabe,0,"[{'id': 9648, 'name': 'Mystery'}, {'id': 18, '...",114464,zh,杀生,1.190345,[],"[{'iso_3166_1': 'CN', 'name': 'China'}]",2012-04-28,0.0,108.0,"[{'iso_639_1': 'zh', 'name': '普通话'}]",Released,Design of Death,False,7.0,6.0,3.500000
44366,False,"{'id': 69788, 'name': 'Sharpe Collection', 'po...",0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",70133,en,Sharpe's Rifles,1.591882,"[{'name': 'Central', 'id': 3649}, {'name': 'Pi...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",1993-05-05,0.0,102.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Sharpe's Rifles,False,5.6,27.0,3.416667
44442,False,not availabe,3000000,"[{'id': 80, 'name': 'Crime'}, {'id': 27, 'name...",135210,ru,Zhest,0.811005,"[{'name': 'Arnold and Gregor Production', 'id'...","[{'iso_3166_1': 'RU', 'name': 'Russia'}]",2006-03-26,0.0,110.0,"[{'iso_639_1': 'ru', 'name': 'Pусский'}]",Released,Junk,False,3.5,6.0,4.500000
44967,False,not availabe,2196531,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",26147,fi,FC Venus,0.947509,"[{'name': 'Talent House', 'id': 4463}]","[{'iso_3166_1': 'FI', 'name': 'Finland'}]",2005-12-30,2411594.0,107.0,"[{'iso_639_1': 'fi', 'name': 'suomi'}]",Released,FC Venus,False,5.6,10.0,3.750000

In [26]:
recommended_movies = recommended_movies.sort_values(by='popularity', ascending=False) # Criteria 4
recommended_movies

,adult,belongs_to_collection,budget,genres,id,original_language,original_title,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,title,video,vote_average,vote_count,rating
12282,False,not availabe,75000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",6538,en,Charlie Wilson's War,9.979162,"[{'name': 'Universal Pictures', 'id': 33}, {'n...","[{'iso_3166_1': 'US', 'name': 'United States o...",2007-12-19,119000410.0,102.0,"[{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso...",Released,Charlie Wilson's War,False,6.5,342.0,3.468254
12187,False,not availabe,70000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",2310,en,Beowulf,9.951195,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",2007-11-05,195735876.0,115.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Beowulf,False,5.5,855.0,3.604167
1336,False,"{'id': 112399, 'name': 'Under Siege Collection...",35000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",8845,en,Under Siege,9.918269,"[{'name': 'Regency Enterprises', 'id': 508}, {...","[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...",1992-10-08,156563139.0,103.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Under Siege,False,6.1,405.0,3.500000
1578,False,not availabe,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",1959,en,Swept from the Sea,9.688237,"[{'name': 'Tapson Steel Films Productions', 'i...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",1998-01-23,0.0,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Swept from the Sea,False,6.5,12.0,3.613333
14710,False,"{'id': 2396, 'name': 'Asterix and Obelix Colle...",97250400,"[{'id': 14, 'name': 'Fantasy'}, {'id': 12, 'na...",2395,fr,Astérix aux Jeux Olympiques,9.671944,"[{'name': 'Constantin Film', 'id': 47}, {'name...","[{'iso_3166_1': 'BE', 'name': 'Belgium'}, {'is...",2008-01-13,132900000.0,116.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,Asterix at the Olympic Games,False,5.0,486.0,3.841308
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23379,False,not availabe,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",94752,en,The Doll Squad,0.003013,[],[],1973-09-19,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Doll Squad,False,5.5,4.0,4.000000
40424,False,not availabe,0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",67255,ja,Gyakufunsha kazoku,0.002001,"[{'name': 'Art Theatre Guild', 'id': 9181}, {'...","[{'iso_3166_1': 'JP', 'name': 'Japan'}]",1984-06-24,0.0,102.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,The Crazy Family,False,6.4,7.0,3.937198
1739,False,not availabe,0,"[{'id': 53, 'name': 'Thriller'}]",73135,en,Ratchet,0.001223,[],"[{'iso_3166_1': 'US', 'name': 'United States o...",1996-09-12,0.0,114.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Ratchet,False,0.0,0.0,4.000000
23985,False,not availabe,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",41810,en,Alligator Eyes,0.000844,[],"[{'iso_3166_1': 'US', 'name': 'United States o...",1990-01-01,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Alligator Eyes,False,0.0,0.0,3.500000
26105,False,not availabe,0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",68659,en,The Horsemen,0.000844,"[{'name': 'Columbia Pictures Corporation', 'id...","[{'iso_3166_1': 'US', 'name': 'United States o...",1971-08-16,0.0,109.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Horsemen,False,6.0,5.0,3.513514

In [27]:
#it is recommending many movies... 
#Now we write a code for top 5 recommendations only with movie titles
top_5_recommendations = recommended_movies.head(5)
top_5_recommendations['title']

12282            Charlie Wilson's War
12187                         Beowulf
1336                      Under Siege
1578               Swept from the Sea
14710    Asterix at the Olympic Games
Name: title, dtype: object